// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChz_XAzt2AR2xOwgLejVNA5TzIQ3K2KXQ',
    appId: '1:858113696272:web:501d953b97ccb9ab88a095',
    messagingSenderId: '858113696272',
    projectId: 'itinerary-voyager',
    authDomain: 'itinerary-voyager.firebaseapp.com',
    storageBucket: 'itinerary-voyager.firebasestorage.app',
    measurementId: 'G-8WBS1DHJVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw8lLnv_dpPH1g4QAEYneV_EahRXRz2Wk',
    appId: '1:858113696272:android:2668505633438fe188a095',
    messagingSenderId: '858113696272',
    projectId: 'itinerary-voyager',
    storageBucket: 'itinerary-voyager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQnbtr-IhCAzYkTT5jYf5Ti9jtOmEwQu8',
    appId: '1:858113696272:ios:53c8da129fd6b66c88a095',
    messagingSenderId: '858113696272',
    projectId: 'itinerary-voyager',
    storageBucket: 'itinerary-voyager.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQnbtr-IhCAzYkTT5jYf5Ti9jtOmEwQu8',
    appId: '1:858113696272:ios:53c8da129fd6b66c88a095',
    messagingSenderId: '858113696272',
    projectId: 'itinerary-voyager',
    storageBucket: 'itinerary-voyager.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChz_XAzt2AR2xOwgLejVNA5TzIQ3K2KXQ',
    appId: '1:858113696272:web:fa0915accb85d9ee88a095',
    messagingSenderId: '858113696272',
    projectId: 'itinerary-voyager',
    authDomain: 'itinerary-voyager.firebaseapp.com',
    storageBucket: 'itinerary-voyager.firebasestorage.app',
    measurementId: 'G-QR34ZHLBPF',
  );
}
