import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

// Firebase options generated by FlutterFire CLI
import 'firebase_options.dart';

// Controller
import 'controller/itinerary_controller.dart';

// Pages
import 'view/login_page.dart';
import 'view/home_page.dart';
import 'view/itinerary_form_page.dart';
import 'view/about_us_page.dart';
import 'view/contact_us_page.dart';
import 'view/profile_page.dart';
import 'view/settings_page.dart';
import 'view/itinerary_summary_page.dart'; // Optional: if you want to add to routes

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const TravelApp());
}

class TravelApp extends StatelessWidget {
  const TravelApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ItineraryController()),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Travel App',
        theme: ThemeData(
          primarySwatch: Colors.teal,
          scaffoldBackgroundColor: Colors.white,
          appBarTheme: const AppBarTheme(
            backgroundColor: Colors.teal,
            foregroundColor: Colors.white,
          ),
        ),
        initialRoute: '/',
        routes: {
          '/': (context) => const LoginPage(),
          '/home': (context) => const HomePage(),
          '/generator': (context) => const ItineraryFormPage(),
          '/about': (context) => const AboutUsPage(),
          '/contact': (context) => const ContactUsPage(),
          '/profile': (context) => const ProfilePage(),
          '/settings': (context) => const SettingsPage(),
          // '/summary': (context) => ItinerarySummaryPage(...), // usually passed via Navigator directly
        },
      ),
    );
  }
}
